export default {
  WON: [
    'https://media.giphy.com/media/SABpzb2ivrS0g4Hgbb/giphy.gif',
    'https://media.giphy.com/media/l0HUnQR733uhm48UM/giphy.gif',
    'https://media.giphy.com/media/JZdLY4pqggtfXbvxLh/giphy.gif',
    'https://media.giphy.com/media/Id1Ay5MD5IsF6Or51v/giphy.gif',
    'https://media.giphy.com/media/lSPtp0kCFqKsgtsQ8k/giphy.gif',
    'https://media.giphy.com/media/3Ow8CIumFRlQXpoVyC/giphy.gif',
    'https://media.giphy.com/media/LOzyexjYyXe7cHSaR0/giphy.gif',
    'https://media.giphy.com/media/QvpcFx1IJSdjXZl5gW/giphy.gif',
    'https://media.giphy.com/media/Qadbv0ccmSrJL9Vlwj/giphy.gif',
    'https://giphy.com/clips/studiosoriginals-tuxedo-tux-gameshow-host-tdKwUz6W6TkYZfjqMe',
  ],
  LOST: [
    'https://media.giphy.com/media/L8a5NHroNWv6nP1YxR/giphy.gif',
    'https://media.giphy.com/media/V9T8PfurFuZH90QzOI/giphy.gif',
    'https://media.giphy.com/media/KbZEMiWBFdynuQUobJ/giphy.gif',
    'https://media.giphy.com/media/K5cmwx0k35BDPoCtjm/giphy.gif',
    'https://media.giphy.com/media/aENYXCbGTCRswKX8kz/giphy.gif',
    'https://media.giphy.com/media/ifedoSkBkcKj4ugEd1/giphy.gif',
    'https://media.giphy.com/media/lMfjWfHEq9y9GI5kaH/giphy.gif',
    'https://media.giphy.com/media/RlAy3QyQiZrnVU5n40/giphy.gif',
    'https://media.giphy.com/media/8v0BF2BS4S7V6/giphy.gif',
    'https://media.giphy.com/media/xT0xeyk3bg0amMtF6g/giphy.gif',
    'https://media.giphy.com/media/jY8oFm2PGd0lJX3dkt/giphy.gif',
    'https://media.giphy.com/media/eJ4j2VnYOZU8qJU3Py/giphy.gif',
    'https://media.giphy.com/media/5MtOIdkHhxPFu/giphy.gif',
  ],
};
